name = "DrakanHex"
author = "alexyzer"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7bc68a7e5c009ccc799d8e88612180e5f1f3110310cd585ce28a3069e986965"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
