name = "DrakanHex"
author = "alexyzer"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b972225fd6b7e86403d91e858f76ac916cf222d60f36d5f1d1a38e1ec9bdcdbe"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
