name = "DrakanHex"
author = "alexyzer"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "904700e39098214e3875f3918a70e633119bc0dd84dc06b3568f7199917dba31"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
