name = "DrakanHex6"
author = "DrakanHex"
version = "6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d89316aecc9a884c0d2a9268615eb27bb91633059df99248a0d0a7905d7f3a4"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
