name = "DrakanHex6"
author = "DrakanHex"
version = "6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "287f9ee1644617d5da915ed365ce3ae32d6235be652e43072fbbbe11355f9d03"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
