name = "DrakanHex6"
author = "DrakanHex"
version = "6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2a3093d7a419f027fd11c9c025f834bd983d763ca193b2eb4e09fd325b27092"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
